#75
JornDeBruin1/Chez_leo pull request #78
Opened 2024-11-21 11:58 UTC by PapaYosif

2024-11-22 08:24 UTC, FlorisGC requested changes
Kan je de titel aanpassen of description van de PR zodat ik weet wat ik moet testen?
Want in de commit names staat niks wat mij uitlegt wat je doet.

2024-11-25 09:58 UTC, FlorisGC requested changes
Wanneer ik naar de bestel pagina ga dan krijg ik dit:
![brave_goZzlhg2EG](https://github.com/user-attachments/assets/0893173d-b702-4410-b650-cd7d4e5fb270)

2024-11-25 11:35 UTC, JesseGroenen approved these changes

2024-11-25 11:36 UTC, JesseGroenen approved these changes

2024-11-25 11:56 UTC, FlorisGC approved these changes

2024-11-25 11:56 UTC, merged